GarageSourceCode/src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnnonceRepository::class)]
class Annonce
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id = null;

    #[ORM\Column(length: 20)]
    public ?string $brand = null;

    #[ORM\Column(length: 30)]
    public ?string $model = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    public ?string $description = null;

    #[ORM\Column]
    public ?int $year = null;

    #[ORM\Column]
    public ?int $mileage = null;

    #[ORM\Column(length: 20)]
    public ?string $fuel_type = null;

    #[ORM\Column(length: 20)]
    public ?string $transmission = null;

    #[ORM\Column]
    public ?int $price = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $imgPath1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $imgPath2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $imgPath3 = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $imgPath4 = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $imgPath5 = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getMileage(): ?int
    {
        return $this->mileage;
    }

    public function setMileage(int $mileage): static
    {
        $this->mileage = $mileage;

        return $this;
    }

    public function getFuelType(): ?string
    {
        return $this->fuel_type;
    }

    public function setFuelType(string $fuel_type): static
    {
        $this->fuel_type = $fuel_type;

        return $this;
    }

    public function getTransmission(): ?string
    {
        return $this->transmission;
    }

    public function setTransmission(string $transmission): static
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getImgPath1(): ?string
    {
        return $this->imgPath1;
    }

    public function setImgPath1(?string $imgPath1): static
    {
        $this->imgPath1 = $imgPath1;

        return $this;
    }

    public function getImgPath2(): ?string
    {
        return $this->imgPath2;
    }

    public function setImgPath2(?string $imgPath2): static
    {
        $this->imgPath2 = $imgPath2;

        return $this;
    }

    public function getImgPath3(): ?string
    {
        return $this->imgPath3;
    }

    public function setImgPath3(?string $imgPath3): static
    {
        $this->imgPath3 = $imgPath3;

        return $this;
    }

    public function getImgPath4(): ?string
    {
        return $this->imgPath4;
    }

    public function setImgPath4(?string $imgPath4): static
    {
        $this->imgPath4 = $imgPath4;

        return $this;
    }

    public function getImgPath5(): ?string
    {
        return $this->imgPath5;
    }

    public function setImgPath5(?string $imgPath5): static
    {
        $this->imgPath5 = $imgPath5;

        return $this;
    }
}

GarageSourceCode/src/Entity/ContactInfo.php
<?php

namespace App\Entity;

use App\Repository\ContactInfoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactInfoRepository::class)]
class ContactInfo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80, nullable: true)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 80, nullable: true)]
    private ?string $e_mail = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEMail(): ?string
    {
        return $this->e_mail;
    }

    public function setEMail(?string $e_mail): static
    {
        $this->e_mail = $e_mail;

        return $this;
    }
}

GarageSourceCode/src/Entity/ContactRequests.php
<?php

namespace App\Entity;

use App\Repository\ContactRequestsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactRequestsRepository::class)]
class ContactRequests
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $user_firstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $user_lastName = null;

    #[ORM\Column(length: 255)]
    private ?string $user_eMail = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $user_phoneNumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $subject = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $user_message = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserFirstName(): ?string
    {
        return $this->user_firstName;
    }

    public function setUserFirstName(string $user_firstName): static
    {
        $this->user_firstName = $user_firstName;

        return $this;
    }

    public function getUserLastName(): ?string
    {
        return $this->user_lastName;
    }

    public function setUserLastName(string $user_lastName): static
    {
        $this->user_lastName = $user_lastName;

        return $this;
    }

    public function getUserEMail(): ?string
    {
        return $this->user_eMail;
    }

    public function setUserEMail(string $user_eMail): static
    {
        $this->user_eMail = $user_eMail;

        return $this;
    }

    public function getUserPhoneNumber(): ?string
    {
        return $this->user_phoneNumber;
    }

    public function setUserPhoneNumber(string $user_phoneNumber): static
    {
        $this->user_phoneNumber = $user_phoneNumber;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): static
    {
        $this->subject = $subject;

        return $this;
    }

    public function getUserMessage(): ?string
    {
        return $this->user_message;
    }

    public function setUserMessage(?string $user_message): static
    {
        $this->user_message = $user_message;

        return $this;
    }
}

GarageSourceCode/src/Entity/Reviews.php
<?php

namespace App\Entity;

use App\Repository\ReviewsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReviewsRepository::class)]
class Reviews
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(targetEntity: 'User', inversedBy: 'reviews')]
    #[ORM\JoinColumn(nullable: true, onDelete:'SET NULL')]
    private ?User $user_mail = null;

    #[ORM\Column]
    private ?int $grade = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $review = null;

    #[ORM\Column]
    private ?bool $was_moderated = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserMail(): ?User
    {
        return $this->user_mail;
    }

    public function setUserMail(User $user_mail): static
    {
        $this->user_mail = $user_mail;

        return $this;
    }

    public function getGrade(): ?int
    {
        return $this->grade;
    }

    public function setGrade(int $grade): static
    {
        $this->grade = $grade;

        return $this;
    }

    public function getReview(): ?string
    {
        return $this->review;
    }

    public function setReview(?string $review): static
    {
        $this->review = $review;

        return $this;
    }

    public function isWasModerated(): ?bool
    {
        return $this->was_moderated;
    }

    public function setWasModerated(bool $was_moderated): static
    {
        $this->was_moderated = $was_moderated;

        return $this;
    }
}

GarageSourceCode/templates/Edit_contact_info.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier les informations de contact{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'><a class='breadcrumb' href="./espace-personnel">Espace personnel ></a></li>
        <li class='breadcrumb'>Modification de contact</li>
    </ul>
    <div class='adaptive-container'>
        <div class='adaptive-list'>
            <h2 class='f-2'>Modification des informations de contact</h2>
            {{ form_start(form) }}
            {{ form_widget(form) }}
                <button
                    type='submit'
                    class='btn padding-10'>
                    Envoyer
                </button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

GarageSourceCode/templates/Edit_hours.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier les horaires de travail{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'><a class='breadcrumb' href="./espace-personnel">Espace personnel ></a></li>
        <li class='breadcrumb'>Modification des horaires</li>
    </ul>
    <div class='adaptive-container'>
        <div class='adaptive-list'>
            <h2 class='f-2'>Modification des horaires</h2>
            {{ form_start(form) }}
            {{ form_widget(form) }}
                <button
                    type='submit'
                    class='btn padding-10'>
                    Envoyer
                </button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

GarageSourceCode/templates/add_staff.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau compte employé{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'><a class='breadcrumb' href="./espace-personnel">Espace personnel ></a></li>
        <li class='breadcrumb'>Nouveau compte employé</li>
    </ul>
    <div class='adaptive-container'>
        <div class='adaptive-list'>
            <h2 class='f-2'>Nouveau compte employé</h2>
            {{ form_errors(registrationForm) }}

            {{ form_start(registrationForm) }}
                {{ form_row(registrationForm.email) }}
                {{ form_row(registrationForm.plainPassword, {
                    label: 'Mot de passe'
                }) }}

                <button type="submit" class="btn">Enregistrer</button>
            {{ form_end(registrationForm) }}
        </div>
    </div>
{% endblock %}

GarageSourceCode/templates/annoncement.html.twig
{% extends 'base.html.twig' %}

{% block title %} Annonce {{annonce.brand}} {{annonce.model}}{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'><a class='breadcrumb' href="./announcements">Annonces ></a></li>
        <li class='breadcrumb'>{{annonce.brand}} {{annonce.model}}</li>
    </ul>
    <div class='annonce-main-block'>
        <div class='slider'>
            <button onclick='photoSlider.sliderLeft()' class='arrow-btn'><</button>
            <div id='vp3' class='sliderViewPort'>
                <div id='bnd3' class='slider-band'>
                    {% if annonce.imgPath1 != null%}
                        <img class='slider-img' src='{{annonce.imgPath1}}'>
                    {% endif %}
                    {% if annonce.imgPath2 != null%}
                        <img class='slider-img' src='{{annonce.imgPath2}}'>
                    {% endif %}
                    {% if annonce.imgPath3 != null%}
                        <img class='slider-img' src='{{annonce.imgPath3}}'>
                    {% endif %}
                    {% if annonce.imgPath4 != null%}
                        <img class='slider-img' src='{{annonce.imgPath4}}'>
                    {% endif %}
                    {% if annonce.imgPath5 != null%}
                        <img class='slider-img' src='{{annonce.imgPath5}}'>
                    {% endif %}
                </div>
            </div>
            <button onclick='photoSlider.sliderRight()' class='arrow-btn'>></button>
        </div>  
        <div class='info'>
            <div>
            <p class='f-3 t-center padding-10'>{{annonce.brand}} {{annonce.model}}</p>
            <p class='f-2'><img src='sources/img/year_icon.png' class='annonce-card-info-description-img'>{{annonce.year}}</p>
            <p class='f-2'><img src='sources/img/mileage_icon.png' class='annonce-card-info-description-img'>{{annonce.mileage}}</p>
            <p class='f-2'><img src='sources/img/gas_icon.png' class='annonce-card-info-description-img'>{{annonce.fuelType}}</p>
            <p class='f-2'><img src='sources/img/transmission_icon.png' class='annonce-card-info-description-img'>{{annonce.transmission}}</p>
            </div>
            <div class='info-2'>
            <p class='f-3 t-center'>{{annonce.price}} €</p>
            {% if app.user %}
                {% if (app.user.roles[0] is same as('ROLE_ADMIN')) or (app.user.roles[0] is same as('ROLE_STAFF')) %}
                    <button 
                        class='btn margin-10 t-center'
                        onclick= 'location.href="./modifier-annonce"+ {{ annonce.id }}'
                        >
                        Modifier
                    </button>
                    <button 
                        class='btn margin-10 t-center'
                        onclick= 'location.href="./supprimer-annonce"+ {{ annonce.id }}'
                        >
                        Supprimer
                    </button>
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>
    <div class='description-container'>
        <p class='f-3'>Description</p>
        <p class='f-2'>{{annonce.description|nl2br|raw }}</p>
    </div>

    {% if requestConfirm %}
        <p class='t-center f-3 padding-30'>Votre demande a eté prise en compte !</p>
    {% else %}
         <p class='t-center f-2 padding-30'>Vous avez des questions sur cette annonce ?</p>

        <p class='t-center f-1'>Remplissez ce formulaire et on vous contactera au plus bref délai !</p>

        <div class='centered-content'>
            {{ form_start(form, {'attr': {'class': 'form-inner-container'}}) }}

                {{ form_widget(form) }}
                <button
                    type='sybmit'
                    class='btn padding-10'>
                    Envoyer
                </button>

            {{ form_end(form)}}
        </div>
    {% endif %}
    
    <script src='slider.js'></script>
    <script>
        let photoSlider = new Slider('vp3','bnd3','.slider-img')
        photoSlider.setShownOnMobile(1)
        photoSlider.setShownOnDesctop(1)
    </script>
{% endblock %}

GarageSourceCode/templates/annoncements.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'>Annonces</li>
    </ul>

    <div class='annonces-page-container'>
        <div class='filtres-container'>

            <label class='t-center f-3'>Filtres</label>
            <label class='f-2'>Prix</label>
            <input class='input' id='ipmin' type="text" placeholder='min'></input>
            <input class='input' id='ipmax' type="text" placeholder='max'></input>
            <label class='f-2'>Kilométrage</label>
            <input class='input' id='ikmin' type="text" placeholder='min'></input>
            <input class='input' id='ikmax' type="text" placeholder='max'></input>
            <label class='f-2'>Année</label>
            <input class='input' id='iymin' type="text" placeholder='min'></input>
            <input class='input' id='iymax'  type="text" placeholder='max'></input>

            <label class='t-center f-3 padding-10'>Trier</label>
            
            <p class='f-var'>
            <label for="priceUp">Prix croissant</label>
            <input id='priceUp' type="radio" name="Sort"></input>
            </p>
            <p class='f-var'>
            <label for="priceDown">Prix décroissant</label>
            <input id='priceDown' type="radio" name="Sort"></input>
            </p>
            <p class='f-var'>
            <label for="mileageUp">Kilometrage croissant</label>
            <input id='mileageUp' type="radio" name="Sort"></input>
            </p>
            <p class='f-var'>
            <label for="mileageDown">Kilometrage décroissant</label>
            <input id='mileageDown' type="radio" name="Sort"></input>
            </p>
            <p class='f-var'>
            <label for="yearUp">Année croissant</label>
            <input id='yearUp' type="radio" name="Sort"></input>
            </p>
            <p class='f-var'>
            <label for="yearDown">Anne décroissant</label>
            <input id='yearDown' type="radio" name="Sort"></input>
            </p>


            <div class='centered-content'>
                <button id='filtres-btn' class='btn'>Appliquer les filtres</button>
                <button id='filtres-erase-btn' class='btn'>Effacer les filtres</button>
            </div>
            
        </div>
        <div class='annonces-list'>
            <div class='annonces-header'>
                <div class='annonces-header-element'>
                    <p>{{ annonces|length }} Annonces au total</P>
                </div>
            </div>
            <div id='ac1' class='annonces-blocks-list'>
            </div>
        </div>
    </div>
    <script>
        let annonces = {{ annoncesJSON|raw }}
    </script>
    <script src='annonces.js'>
    </script>
{% endblock %}

GarageSourceCode/templates/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'>Contact</li>
    </ul>

    <p class='t-center f-1'>Une question à poser ?</p>
    <p class='t-center f-1'>Un devis à renseigner ?</p>
    <p class='t-center f-3 padding-10'>CONTACTEZ-NOUS PAR</p>

    <div class='contact-element'>
        <img class='contact-icon padding-10' src='sources/img/mail_icon.png'>
        <p class=' padding-10 contact-p'>{{ contact.eMail}}</p>
    </div>

    <p class='t-center f-2 padding-30'>OU</p>

    <div class='contact-element'>
        <img class='contact-icon padding-10' src='sources/img/phone_icon.png'>
        <p class=' padding-10 contact-p'>{{ contact.phonenumber }}</p>
    </div>

    <p class='t-center f-2 padding-30'>OU</p>

        <p class='t-center f-1'>Remplissez ce formulaire et on vous contactera au plus bref délai!</p>

    <div class='centered-content'>
        {{ form_start(form, {'attr': {'class': 'form-inner-container'}}) }}

            {{ form_widget(form) }}
            <button
                type='sybmit'
                class='btn padding-10'>
                Envoyer
            </button>

        {{ form_end(form)}}
    </div>

{% endblock %}

GarageSourceCode/templates/contact_requests.html.twig
{% extends 'base.html.twig' %}

{% block title %}Houraires de travail{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'><a class='breadcrumb' href="./espace-personnel">Espace personnel ></a></li>
        <li class='breadcrumb'>Demandes de contact</li>
    </ul>
        <h3 class='f-3 t-center'>Liste des contacts</h3>
        {% if contactRequests|length < 1 %}
            <h1 class='f-1 t-center'>Aucun nouvelle demande de contact</h1>
        {% endif %}
        {% for contactRequest in contactRequests %}
        <div class='adaptive-container'>
            <div class='adaptive-list'>
                <p class='f-1 t-left'>Prénom</p>
                <p class='f-1 t-left bg-1'>{{contactRequest.userFirstName}} </p>
                <p class='f-1 t-left'>Nom</p>
                <p class='f-1 t-left bg-1'>{{contactRequest.userLastName}}</p>
                <p class='f-1 t-left'>Mail</p>
                <p class='f-1 t-left bg-1'>{{contactRequest.userEmail}} </p>
                <p class='f-1 t-left'>Numéro</p>
                <p class='f-1 t-left bg-1'>{{contactRequest.userPhoneNumber}} </p>
                <p class='f-1 t-left'>Sujet de message</p>
                <p class='f-1 t-left bg-1'>{{contactRequest.subject}} </p>
                <p class='f-1 t-left'>Message</p>
                <p class='f-1 t-left bg-1'>{{contactRequest.userMessage}} </p>
                <br>
                <button
                    class='btn',
                    onclick= 'location.href="./supprimer-demande"+ {{ contactRequest.id }}'
                    >
                    supprimer
                </button>
                <br>
            </div>
        </div>
        {% endfor %}
{% endblock %}

GarageSourceCode/templates/edit_Announcment.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier annonce{% endblock %}

{% block content %}
<ul class='breadcrumbs'>
    <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
    <li class='breadcrumb'><a class='breadcrumb' href="./espace-personnel">Espace personnel ></a></li>
    <li class='breadcrumb'>Nouvelle annonce</li>
</ul>
<div class='adaptive-container'>
    <div class='adaptive-list'>
    <h2 class='f-2'>Modification de l'annonce</h2>
    {{ form_start(form) }}
    {{ form_widget(form) }}
            <button
                type='submit'
                class='btn padding-10'>
                Envoyer
            </button>
    {{ form_end(form) }}
{% endblock %}

GarageSourceCode/templates/moderer_review.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modération{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'><a class='breadcrumb' href="./espace-personnel">Espace personnel ></a></li>
        <li class='breadcrumb'>Modération</li>
    </ul>
    <h3 class='f-3 t-center'>Modération des commentaires</h3>
    {% if reviews|length < 1 %}
        <h1 class='f-1 t-center'>Aucun nouveau commentaire</h1>
    {% endif %}
    {% for review in reviews %}
    <div class='adaptive-container'>
        <div class='adaptive-list'>
            <p class='f-1 t-left'>Email</p>
            <p class='f-1 t-left bg-1'>{{review.userMail.eMail}}</p>
            <p class='f-1 t-left'>Note</p>
            <p class='f-1 t-left bg-1'>{{review.grade}}</p>
            <p class='f-1 t-left'>Avis</p>
            <p class='f-1 t-left bg-1'>{{review.review}}</p>
            <br>
            <button 
                    class='btn' 
                    onclick= 'location.href="./approuver"+ {{ review.id }}'>
                    Approuver
            </button>
            <button 
                    class='btn' 
                    onclick= 'location.href="./supprimer-avis"+ {{ review.id }}'>
                    Supprimer
            </button>
        </div>
    </div>
    {% endfor %}
{% endblock %}

GarageSourceCode/templates/private_space.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace personnel{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'>Espace personnel</li>
    </ul>
    <h1 class='t-center f-3'>Bienvenue {{ app.user.email}}! </h1>
    {% if app.user.roles[0] is same as('ROLE_ADMIN')  %}
        <h1 class='t-center f-3'>Utilisateur avec droits ADMINISTRATEUR</h1>
    {% endif %}
    {% if app.user.roles[0] is same as('ROLE_STAFF')  %}
        <h1 class='t-center f-3'>Utilisateur avec droits EMPLOYÉ</h1>
    {% endif %}
    <div class='adaptive-container'>
        <div class='adaptive-list'>
            <h2 class='t-center f-2 adaptive-title'>Functionalités de l'espace personnel</h2>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./ajouter-avis'>Laisser un avis</a></p>
        {% if (app.user.roles[0] is same as('ROLE_ADMIN')) or (app.user.roles[0] is same as('ROLE_STAFF')) %}
            <h2 class='t-center f-2 adaptive-title'>Fonctionnalités dédiées aux employés</h2>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./ajouter-annonce'>Ajouter une voiture à la vente</a></p>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./contact-liste'>Afficher les demandes de contact ({{ contactReq|length }})</a></p>
        {% endif %}
        {% if app.user.roles[0] is same as('ROLE_ADMIN') %}
            <h2 class='t-center f-2 adaptive-title'>Panneau d'administration</h2>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./ajouter-service'>Ajouter une prestation</a></p>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./ajouter-emploie'>Ajouter un compte employé</a></p>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./list-emploie'>Afficher la liste des utilisateurs</a></p>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./hours-edit'>Modifier les horaires de travaille</a></p>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./contact-edit'>Modifier les informations de contact</a></p>
            <p class='adaptive-btn-p f-1'><a class='adaptive-btn f-1' href='./moderation'>Modérer les nouveaux commentaires ({{ reviews|length }})</a></p>
            <br>
        </div>
    </div>
    {% endif %}
{% endblock %}

GarageSourceCode/templates/reviews.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des commentaires{% endblock %}

{% block content %}
    <ul class='breadcrumbs'>
        <li class='breadcrumb'><a class='breadcrumb' href="./">Accueil ></a></li>
        <li class='breadcrumb'>Liste des commentaires</li>
    </ul>
    <h3 class='f-3 t-center'>Liste des commentaires</h3>
        {% for avis in reviews|reverse %}
        <div class='adaptive-container'>
            <div class='adaptive-list'>
                <p class='f-2 t-left'>{{avis.userMail.eMail}}</p>
                <div class='stars-container t-left'>
                    {% if avis.grade > 0 %}
                        <img class='star full'>
                    {% else %}
                        <img class='star empty'>
                    {% endif %}
                    {% if avis.grade > 1 %}
                        <img class='star full'>
                    {% else %}
                        <img class='star empty'>
                    {% endif %}
                    {% if avis.grade > 2 %}
                        <img class='star full'>
                    {% else %}
                        <img class='star empty'>
                    {% endif %}
                    {% if avis.grade > 3 %}
                        <img class='star full'>
                    {% else %}
                        <img class='star empty'>
                    {% endif %}
                    {% if avis.grade > 4 %}
                        <img class='star full'>
                    {% else %}
                        <img class='star empty'>
                    {% endif %}
                </div>
                <p class='f-1 t-left bg-1'>{{ avis.review }}</p>
                <br>
                {% if app.user %}
                    {% if app.user.roles[0] is same as('ROLE_ADMIN') %}
                    <button 
                        class='btn' 
                        onclick= 'location.href="./supprimer-avis"+ {{ avis.id }}'>
                        SUPPRIMER
                    </button>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock %}